### ISSUE TITLE
Can't run a lua example file

### ISSUE THREAD

**Issue by Zireael07** [Blugatroff/diversion#1]
I built the Rust part successfully. Unfortunately trying to run any of the examples fails on the dofile line.

EDIT: Solved by copying the diversion binary to main folder and running everything from there. Should probably be noted in the README

PS, This tool allowed me to do something no other tool managed to - use two numpads as a budget split keyboard <3

**Comment by Kato-Dax** [comment]
Thank you for the report!

The three lua files which diversion depends on are now embedded into the final executable, so you should now be able to run it from anywhere!
Could you try recompiling with the newest commit and checking whether it now works as you had initially expected?

I wrote the README and examples, knowing there had to be other people, with similarly unusual keyboard preference as mine, who could appreciate this hacky little tool.
I'm very happy you found it practical enough to be helpful! :)

**Comment by Zireael07** [comment]
Embedding the files means it's now super hard to fix issues with the codes (I keep discovering them as I go)

So far:
1) Q and W have the same code
2) ditto T and Y
3) P is listed twice, O is missing
4) Backspace is missing and so is Right Shift

**Comment by Kato-Dax** [comment]
You can still just overwrite the global variables from codes.lua anywhere in your script. There is nothing special about the now embedded definitions and you could even continue using `dofile "codes.lua"` like before, although of course that would sort of defeat the point of having them built in :)

But yeah it's true, embedding these scripts makes quick fixes much more involved.

About the wrong, missing and duplicated keycodes, as you can tell i just added them willy nilly as i went along and it shows xD
